// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stateChange.proto

package stateChange

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ActionType int32

const (
	Read  ActionType = 0
	Write ActionType = 1
)

var ActionType_name = map[int32]string{
	0: "Read",
	1: "Write",
}

var ActionType_value = map[string]int32{
	"Read":  0,
	"Write": 1,
}

func (ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e577663eebb0888, []int{0}
}

type StateAccesses struct {
	StateAccess []*StateAccess `protobuf:"bytes,1,rep,name=StateAccess,proto3" json:"stateAccess"`
}

func (m *StateAccesses) Reset()      { *m = StateAccesses{} }
func (*StateAccesses) ProtoMessage() {}
func (*StateAccesses) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e577663eebb0888, []int{0}
}
func (m *StateAccesses) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StateAccesses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *StateAccesses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateAccesses.Merge(m, src)
}
func (m *StateAccesses) XXX_Size() int {
	return m.Size()
}
func (m *StateAccesses) XXX_DiscardUnknown() {
	xxx_messageInfo_StateAccesses.DiscardUnknown(m)
}

var xxx_messageInfo_StateAccesses proto.InternalMessageInfo

func (m *StateAccesses) GetStateAccess() []*StateAccess {
	if m != nil {
		return m.StateAccess
	}
	return nil
}

type StateAccess struct {
	Type            ActionType        `protobuf:"varint,1,opt,name=Type,proto3,enum=proto.ActionType" json:"type"`
	Index           int32             `protobuf:"varint,2,opt,name=Index,proto3" json:"index"`
	TxHash          []byte            `protobuf:"bytes,3,opt,name=TxHash,proto3" json:"txHash"`
	MainTrieKey     []byte            `protobuf:"bytes,4,opt,name=MainTrieKey,proto3" json:"mainTrieKey"`
	MainTrieVal     []byte            `protobuf:"bytes,5,opt,name=MainTrieVal,proto3" json:"mainTrieVal"`
	Operation       uint32            `protobuf:"varint,6,opt,name=Operation,proto3" json:"operation"`
	DataTrieChanges []*DataTrieChange `protobuf:"bytes,7,rep,name=DataTrieChanges,proto3" json:"dataTrieChanges,omitempty"`
	AccountChanges  uint32            `protobuf:"varint,8,opt,name=AccountChanges,proto3" json:"accountChanges"`
}

func (m *StateAccess) Reset()      { *m = StateAccess{} }
func (*StateAccess) ProtoMessage() {}
func (*StateAccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e577663eebb0888, []int{1}
}
func (m *StateAccess) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StateAccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *StateAccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateAccess.Merge(m, src)
}
func (m *StateAccess) XXX_Size() int {
	return m.Size()
}
func (m *StateAccess) XXX_DiscardUnknown() {
	xxx_messageInfo_StateAccess.DiscardUnknown(m)
}

var xxx_messageInfo_StateAccess proto.InternalMessageInfo

func (m *StateAccess) GetType() ActionType {
	if m != nil {
		return m.Type
	}
	return Read
}

func (m *StateAccess) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *StateAccess) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *StateAccess) GetMainTrieKey() []byte {
	if m != nil {
		return m.MainTrieKey
	}
	return nil
}

func (m *StateAccess) GetMainTrieVal() []byte {
	if m != nil {
		return m.MainTrieVal
	}
	return nil
}

func (m *StateAccess) GetOperation() uint32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

func (m *StateAccess) GetDataTrieChanges() []*DataTrieChange {
	if m != nil {
		return m.DataTrieChanges
	}
	return nil
}

func (m *StateAccess) GetAccountChanges() uint32 {
	if m != nil {
		return m.AccountChanges
	}
	return 0
}

type DataTrieChange struct {
	Type      ActionType `protobuf:"varint,1,opt,name=Type,proto3,enum=proto.ActionType" json:"type"`
	Key       []byte     `protobuf:"bytes,2,opt,name=Key,proto3" json:"key"`
	Val       []byte     `protobuf:"bytes,3,opt,name=Val,proto3" json:"val"`
	Version   uint32     `protobuf:"varint,4,opt,name=Version,proto3" json:"version"`
	Operation uint32     `protobuf:"varint,5,opt,name=Operation,proto3" json:"operation"`
}

func (m *DataTrieChange) Reset()      { *m = DataTrieChange{} }
func (*DataTrieChange) ProtoMessage() {}
func (*DataTrieChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e577663eebb0888, []int{2}
}
func (m *DataTrieChange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DataTrieChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *DataTrieChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTrieChange.Merge(m, src)
}
func (m *DataTrieChange) XXX_Size() int {
	return m.Size()
}
func (m *DataTrieChange) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTrieChange.DiscardUnknown(m)
}

var xxx_messageInfo_DataTrieChange proto.InternalMessageInfo

func (m *DataTrieChange) GetType() ActionType {
	if m != nil {
		return m.Type
	}
	return Read
}

func (m *DataTrieChange) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DataTrieChange) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *DataTrieChange) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DataTrieChange) GetOperation() uint32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.ActionType", ActionType_name, ActionType_value)
	proto.RegisterType((*StateAccesses)(nil), "proto.StateAccesses")
	proto.RegisterType((*StateAccess)(nil), "proto.StateAccess")
	proto.RegisterType((*DataTrieChange)(nil), "proto.DataTrieChange")
}

func init() { proto.RegisterFile("stateChange.proto", fileDescriptor_8e577663eebb0888) }

var fileDescriptor_8e577663eebb0888 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcf, 0x8a, 0xd3, 0x40,
	0x18, 0xcf, 0x6c, 0x9a, 0x76, 0x3b, 0xb5, 0xdd, 0xdd, 0x01, 0x21, 0x2b, 0x38, 0xa9, 0x05, 0xa1,
	0xa8, 0x6d, 0x70, 0xbd, 0xe9, 0xa9, 0x71, 0x45, 0x45, 0x44, 0x18, 0x4b, 0x05, 0x0f, 0xc2, 0x34,
	0x1d, 0xdb, 0x60, 0x9b, 0x29, 0x93, 0xe9, 0xb2, 0xbd, 0xe9, 0x1b, 0xf8, 0x18, 0x9e, 0x7d, 0x0a,
	0xc1, 0x4b, 0x8f, 0x3d, 0x05, 0x9b, 0x5e, 0x24, 0xa7, 0x7d, 0x04, 0x99, 0x69, 0x4b, 0x93, 0x15,
	0x04, 0x4f, 0x99, 0xf9, 0xfd, 0xe3, 0xcb, 0xef, 0x63, 0xe0, 0x49, 0x24, 0xa9, 0x64, 0x4f, 0x47,
	0x34, 0x1c, 0xb2, 0xf6, 0x54, 0x70, 0xc9, 0x91, 0xa5, 0x3f, 0xb7, 0x5a, 0xc3, 0x40, 0x8e, 0x66,
	0xfd, 0xb6, 0xcf, 0x27, 0xee, 0x90, 0x0f, 0xb9, 0xab, 0xe1, 0xfe, 0xec, 0xa3, 0xbe, 0xe9, 0x8b,
	0x3e, 0x6d, 0x5c, 0x8d, 0x1e, 0xac, 0xbe, 0x55, 0x51, 0x1d, 0xdf, 0x67, 0x51, 0xc4, 0x22, 0xf4,
	0x0c, 0x56, 0x32, 0x80, 0x0d, 0xea, 0x66, 0xb3, 0x72, 0x86, 0x36, 0xea, 0x76, 0x86, 0xf1, 0x8e,
	0xd2, 0xd8, 0xa9, 0x44, 0x7b, 0x80, 0x64, 0x7d, 0x8d, 0xef, 0x66, 0x2e, 0x07, 0xb9, 0xb0, 0xd0,
	0x9d, 0x4f, 0x99, 0x0d, 0xea, 0xa0, 0x59, 0x3b, 0x3b, 0xd9, 0xe6, 0x75, 0x7c, 0x19, 0xf0, 0x50,
	0x11, 0xde, 0x61, 0x1a, 0x3b, 0x05, 0x39, 0x9f, 0x32, 0xa2, 0x85, 0xc8, 0x81, 0xd6, 0xcb, 0x70,
	0xc0, 0x2e, 0xed, 0x83, 0x3a, 0x68, 0x5a, 0x5e, 0x39, 0x8d, 0x1d, 0x2b, 0x50, 0x00, 0xd9, 0xe0,
	0xa8, 0x01, 0x8b, 0xdd, 0xcb, 0x17, 0x34, 0x1a, 0xd9, 0x66, 0x1d, 0x34, 0x6f, 0x78, 0x30, 0x8d,
	0x9d, 0xa2, 0xd4, 0x08, 0xd9, 0x32, 0xe8, 0x21, 0xac, 0xbc, 0xa6, 0x41, 0xd8, 0x15, 0x01, 0x7b,
	0xc5, 0xe6, 0x76, 0x41, 0x0b, 0xf5, 0xe0, 0x93, 0x3d, 0x4c, 0xb2, 0x9a, 0xac, 0xa5, 0x47, 0xc7,
	0xb6, 0xf5, 0xb7, 0xa5, 0x47, 0xc7, 0x24, 0xab, 0x41, 0xf7, 0x61, 0xf9, 0xcd, 0x94, 0x09, 0xaa,
	0xfe, 0xc5, 0x2e, 0xd6, 0x41, 0xb3, 0xea, 0x55, 0xd3, 0xd8, 0x29, 0xf3, 0x1d, 0x48, 0xf6, 0x3c,
	0xfa, 0x00, 0x8f, 0xce, 0xa9, 0xa4, 0xca, 0xbb, 0x59, 0x5f, 0x64, 0x97, 0x74, 0xc7, 0x37, 0xb7,
	0x9d, 0xe4, 0x59, 0xef, 0x76, 0x1a, 0x3b, 0xa7, 0x83, 0xbc, 0xe3, 0x01, 0x9f, 0x04, 0x92, 0x4d,
	0xa6, 0x72, 0x4e, 0xae, 0x87, 0xa1, 0xc7, 0xb0, 0xd6, 0xf1, 0x7d, 0x3e, 0x0b, 0xe5, 0x2e, 0xfe,
	0x50, 0x4f, 0x84, 0xd2, 0xd8, 0xa9, 0xd1, 0x1c, 0x43, 0xae, 0x29, 0x1b, 0x3f, 0x01, 0xac, 0xe5,
	0xf3, 0xfe, 0x7f, 0x6f, 0xa7, 0xd0, 0x54, 0x55, 0x1f, 0xe8, 0xde, 0x4a, 0x69, 0xec, 0x98, 0x9f,
	0xd8, 0x9c, 0x28, 0x4c, 0x51, 0xaa, 0x52, 0x73, 0x4f, 0x5d, 0xd0, 0x31, 0x51, 0x18, 0xba, 0x0b,
	0x4b, 0x3d, 0x26, 0x22, 0x55, 0x60, 0x41, 0x8f, 0x5b, 0x49, 0x63, 0xa7, 0x74, 0xb1, 0x81, 0xc8,
	0x8e, 0xcb, 0x37, 0x6d, 0xfd, 0xbb, 0xe9, 0x7b, 0x77, 0x20, 0xdc, 0xcf, 0x89, 0x0e, 0x61, 0x81,
	0x30, 0x3a, 0x38, 0x36, 0x50, 0x19, 0x5a, 0xef, 0x44, 0x20, 0xd9, 0x31, 0xf0, 0xbe, 0x80, 0xc5,
	0x0a, 0x1b, 0xcb, 0x15, 0x36, 0xae, 0x56, 0x18, 0x7c, 0x4e, 0x30, 0xf8, 0x96, 0x60, 0xf0, 0x23,
	0xc1, 0x60, 0x91, 0x60, 0xb0, 0x4c, 0x30, 0xf8, 0x95, 0x60, 0xf0, 0x3b, 0xc1, 0xc6, 0x55, 0x82,
	0xc1, 0xd7, 0x35, 0x36, 0x16, 0x6b, 0x6c, 0x2c, 0xd7, 0xd8, 0x78, 0xff, 0x3c, 0xf3, 0xce, 0xba,
	0x4c, 0x08, 0x7a, 0x3e, 0xa2, 0x22, 0x90, 0x22, 0x70, 0x07, 0x42, 0xb6, 0x86, 0xbc, 0xe5, 0x8f,
	0x68, 0x10, 0xb6, 0x7c, 0x2e, 0x98, 0xab, 0xd6, 0xe7, 0x66, 0x5e, 0xec, 0x93, 0xcc, 0xb9, 0x5f,
	0xd4, 0x95, 0x3e, 0xfa, 0x13, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xb0, 0xbc, 0x29, 0xd3, 0x03, 0x00,
	0x00,
}

func (x ActionType) String() string {
	s, ok := ActionType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *StateAccesses) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StateAccesses)
	if !ok {
		that2, ok := that.(StateAccesses)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.StateAccess) != len(that1.StateAccess) {
		return false
	}
	for i := range this.StateAccess {
		if !this.StateAccess[i].Equal(that1.StateAccess[i]) {
			return false
		}
	}
	return true
}
func (this *StateAccess) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StateAccess)
	if !ok {
		that2, ok := that.(StateAccess)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.Index != that1.Index {
		return false
	}
	if !bytes.Equal(this.TxHash, that1.TxHash) {
		return false
	}
	if !bytes.Equal(this.MainTrieKey, that1.MainTrieKey) {
		return false
	}
	if !bytes.Equal(this.MainTrieVal, that1.MainTrieVal) {
		return false
	}
	if this.Operation != that1.Operation {
		return false
	}
	if len(this.DataTrieChanges) != len(that1.DataTrieChanges) {
		return false
	}
	for i := range this.DataTrieChanges {
		if !this.DataTrieChanges[i].Equal(that1.DataTrieChanges[i]) {
			return false
		}
	}
	if this.AccountChanges != that1.AccountChanges {
		return false
	}
	return true
}
func (this *DataTrieChange) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DataTrieChange)
	if !ok {
		that2, ok := that.(DataTrieChange)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if !bytes.Equal(this.Key, that1.Key) {
		return false
	}
	if !bytes.Equal(this.Val, that1.Val) {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	if this.Operation != that1.Operation {
		return false
	}
	return true
}
func (this *StateAccesses) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&stateChange.StateAccesses{")
	if this.StateAccess != nil {
		s = append(s, "StateAccess: "+fmt.Sprintf("%#v", this.StateAccess)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *StateAccess) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 12)
	s = append(s, "&stateChange.StateAccess{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Index: "+fmt.Sprintf("%#v", this.Index)+",\n")
	s = append(s, "TxHash: "+fmt.Sprintf("%#v", this.TxHash)+",\n")
	s = append(s, "MainTrieKey: "+fmt.Sprintf("%#v", this.MainTrieKey)+",\n")
	s = append(s, "MainTrieVal: "+fmt.Sprintf("%#v", this.MainTrieVal)+",\n")
	s = append(s, "Operation: "+fmt.Sprintf("%#v", this.Operation)+",\n")
	if this.DataTrieChanges != nil {
		s = append(s, "DataTrieChanges: "+fmt.Sprintf("%#v", this.DataTrieChanges)+",\n")
	}
	s = append(s, "AccountChanges: "+fmt.Sprintf("%#v", this.AccountChanges)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DataTrieChange) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&stateChange.DataTrieChange{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Key: "+fmt.Sprintf("%#v", this.Key)+",\n")
	s = append(s, "Val: "+fmt.Sprintf("%#v", this.Val)+",\n")
	s = append(s, "Version: "+fmt.Sprintf("%#v", this.Version)+",\n")
	s = append(s, "Operation: "+fmt.Sprintf("%#v", this.Operation)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringStateChange(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *StateAccesses) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StateAccesses) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StateAccesses) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StateAccess) > 0 {
		for iNdEx := len(m.StateAccess) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StateAccess[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStateChange(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *StateAccess) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StateAccess) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StateAccess) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AccountChanges != 0 {
		i = encodeVarintStateChange(dAtA, i, uint64(m.AccountChanges))
		i--
		dAtA[i] = 0x40
	}
	if len(m.DataTrieChanges) > 0 {
		for iNdEx := len(m.DataTrieChanges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DataTrieChanges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStateChange(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.Operation != 0 {
		i = encodeVarintStateChange(dAtA, i, uint64(m.Operation))
		i--
		dAtA[i] = 0x30
	}
	if len(m.MainTrieVal) > 0 {
		i -= len(m.MainTrieVal)
		copy(dAtA[i:], m.MainTrieVal)
		i = encodeVarintStateChange(dAtA, i, uint64(len(m.MainTrieVal)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.MainTrieKey) > 0 {
		i -= len(m.MainTrieKey)
		copy(dAtA[i:], m.MainTrieKey)
		i = encodeVarintStateChange(dAtA, i, uint64(len(m.MainTrieKey)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintStateChange(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Index != 0 {
		i = encodeVarintStateChange(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if m.Type != 0 {
		i = encodeVarintStateChange(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DataTrieChange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataTrieChange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DataTrieChange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Operation != 0 {
		i = encodeVarintStateChange(dAtA, i, uint64(m.Operation))
		i--
		dAtA[i] = 0x28
	}
	if m.Version != 0 {
		i = encodeVarintStateChange(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Val) > 0 {
		i -= len(m.Val)
		copy(dAtA[i:], m.Val)
		i = encodeVarintStateChange(dAtA, i, uint64(len(m.Val)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintStateChange(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0x12
	}
	if m.Type != 0 {
		i = encodeVarintStateChange(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintStateChange(dAtA []byte, offset int, v uint64) int {
	offset -= sovStateChange(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StateAccesses) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.StateAccess) > 0 {
		for _, e := range m.StateAccess {
			l = e.Size()
			n += 1 + l + sovStateChange(uint64(l))
		}
	}
	return n
}

func (m *StateAccess) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovStateChange(uint64(m.Type))
	}
	if m.Index != 0 {
		n += 1 + sovStateChange(uint64(m.Index))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovStateChange(uint64(l))
	}
	l = len(m.MainTrieKey)
	if l > 0 {
		n += 1 + l + sovStateChange(uint64(l))
	}
	l = len(m.MainTrieVal)
	if l > 0 {
		n += 1 + l + sovStateChange(uint64(l))
	}
	if m.Operation != 0 {
		n += 1 + sovStateChange(uint64(m.Operation))
	}
	if len(m.DataTrieChanges) > 0 {
		for _, e := range m.DataTrieChanges {
			l = e.Size()
			n += 1 + l + sovStateChange(uint64(l))
		}
	}
	if m.AccountChanges != 0 {
		n += 1 + sovStateChange(uint64(m.AccountChanges))
	}
	return n
}

func (m *DataTrieChange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovStateChange(uint64(m.Type))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovStateChange(uint64(l))
	}
	l = len(m.Val)
	if l > 0 {
		n += 1 + l + sovStateChange(uint64(l))
	}
	if m.Version != 0 {
		n += 1 + sovStateChange(uint64(m.Version))
	}
	if m.Operation != 0 {
		n += 1 + sovStateChange(uint64(m.Operation))
	}
	return n
}

func sovStateChange(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStateChange(x uint64) (n int) {
	return sovStateChange(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *StateAccesses) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForStateAccess := "[]*StateAccess{"
	for _, f := range this.StateAccess {
		repeatedStringForStateAccess += strings.Replace(f.String(), "StateAccess", "StateAccess", 1) + ","
	}
	repeatedStringForStateAccess += "}"
	s := strings.Join([]string{`&StateAccesses{`,
		`StateAccess:` + repeatedStringForStateAccess + `,`,
		`}`,
	}, "")
	return s
}
func (this *StateAccess) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForDataTrieChanges := "[]*DataTrieChange{"
	for _, f := range this.DataTrieChanges {
		repeatedStringForDataTrieChanges += strings.Replace(f.String(), "DataTrieChange", "DataTrieChange", 1) + ","
	}
	repeatedStringForDataTrieChanges += "}"
	s := strings.Join([]string{`&StateAccess{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Index:` + fmt.Sprintf("%v", this.Index) + `,`,
		`TxHash:` + fmt.Sprintf("%v", this.TxHash) + `,`,
		`MainTrieKey:` + fmt.Sprintf("%v", this.MainTrieKey) + `,`,
		`MainTrieVal:` + fmt.Sprintf("%v", this.MainTrieVal) + `,`,
		`Operation:` + fmt.Sprintf("%v", this.Operation) + `,`,
		`DataTrieChanges:` + repeatedStringForDataTrieChanges + `,`,
		`AccountChanges:` + fmt.Sprintf("%v", this.AccountChanges) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DataTrieChange) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DataTrieChange{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Key:` + fmt.Sprintf("%v", this.Key) + `,`,
		`Val:` + fmt.Sprintf("%v", this.Val) + `,`,
		`Version:` + fmt.Sprintf("%v", this.Version) + `,`,
		`Operation:` + fmt.Sprintf("%v", this.Operation) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringStateChange(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *StateAccesses) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStateChange
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StateAccesses: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StateAccesses: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateAccess", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStateChange
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStateChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateAccess = append(m.StateAccess, &StateAccess{})
			if err := m.StateAccess[len(m.StateAccess)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStateChange(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStateChange
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StateAccess) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStateChange
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StateAccess: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StateAccess: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= ActionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStateChange
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStateChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = append(m.TxHash[:0], dAtA[iNdEx:postIndex]...)
			if m.TxHash == nil {
				m.TxHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MainTrieKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStateChange
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStateChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MainTrieKey = append(m.MainTrieKey[:0], dAtA[iNdEx:postIndex]...)
			if m.MainTrieKey == nil {
				m.MainTrieKey = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MainTrieVal", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStateChange
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStateChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MainTrieVal = append(m.MainTrieVal[:0], dAtA[iNdEx:postIndex]...)
			if m.MainTrieVal == nil {
				m.MainTrieVal = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operation", wireType)
			}
			m.Operation = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Operation |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataTrieChanges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStateChange
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStateChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataTrieChanges = append(m.DataTrieChanges, &DataTrieChange{})
			if err := m.DataTrieChanges[len(m.DataTrieChanges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountChanges", wireType)
			}
			m.AccountChanges = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccountChanges |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStateChange(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStateChange
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DataTrieChange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStateChange
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataTrieChange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataTrieChange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= ActionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStateChange
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStateChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Val", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStateChange
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStateChange
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Val = append(m.Val[:0], dAtA[iNdEx:postIndex]...)
			if m.Val == nil {
				m.Val = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operation", wireType)
			}
			m.Operation = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Operation |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStateChange(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStateChange
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStateChange(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStateChange
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStateChange
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStateChange
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStateChange
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStateChange
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStateChange        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStateChange          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStateChange = fmt.Errorf("proto: unexpected end of group")
)
